# justauth
justauth:
  enabled: true
  type:
    github:
      client-id: 5c2711630ff813639351
      client-secret: b5101b988548765eaff6577e2c77f71c7c383be9
      redirect-uri: http://localhost:9420/oauth/github/callback
  cache:
    type: redis
    prefix: 'SOCIAL::STATE::'
    timeout: 1h